src/app.config.js
src/components/Footer.js
src/components/RegisterSection.css
src/components/hire-a-talent/hire-a-talent.css
src/components/trusted-by/trustedby.css

fixed sliding images

---

src/Data/data.js
src/components/Advantage.js
src/components/CompanySection.js
src/components/FounderDetails.js

changed text

---

public/index.html
src/components/RegisterSection.js
src/components/hire-a-talent/HireATalent.js

This PR added a tracker script

added a tracker script

---

public/index.html

intalled hotjar

---

src/components/Navbar.css
src/components/Navbar.js

The PR changed the coming soon text

changed the coming soon text

---

package-lock.json
package.json
src/pages/Home.js

added open graph

---

public/index.html

fix opengraph

---

public/index.html

 still fixing og

---

src/components/BottomSection.css
src/components/BottomSection.js
src/components/trusted-by/trustedby.css
src/components/vetting-process/vetting-process.css

modify grid container with the images sizes, adjust the  iframe width on desktop devices and responsive on all devices

modify grid container and image, iframe sizes on all devices

---

src/components/vetting-process/vetting-process.css

adjust vetting video width size

adjust vetting video width

---

src/components/CompanySection.js

mapped through the review content and still working on it, please don't merge yet

mapped through the review content

---

src/components/CompanySection.js

undo changes

---

src/components/CompanySection.js

undo review changes

---

src/components/CompanySection.css
src/components/CompanySection.js

undo review changes version 2

---

src/Data/talents.js
src/components/CompanySection.css

increase height of the swiper slide of the carousel

increase height of the swiper slide

---

src/components/CompanySection.css

reduce p tag font size to 14px of  max-width of 475px small screen devices

reduce p tag font size to 14px of  max-width of 475px small screens

---

src/components/RegisterSection.js
src/components/hire-a-talent/HireATalent.js

modify become a talent form and the post request

modify become a talent form page

---

src/components/RegisterSection.js

add how did you discover us select box implementataion

add how did you discover us select box

---

src/components/RegisterSection.js
src/components/hire-a-talent/HireATalent.js

correct the select tag label contents

correct the select tag label content

---

src/components/RegisterSection.js
src/components/hire-a-talent/HireATalent.js

modify the select tag if others show  a text area and updates data to google sheet

modify the select tag if others show an a text area

---

src/components/hire-a-talent/hire-a-talent.css

change the active color from default color blue to green

change the active color from default color to green

---

src/components/hire-a-talent/hire-a-talent.css

changed select tag color when on hover from the default color to green

change hover color

---

src/components/vetting-process/vetting-process.css

modify the width of the iframe - youtube video

modify the width of the iframe

---

src/components/vetting-process/vetting-process.css

modify the iframe site video spacing and height across screen sizes and responsiveness

modify the iframe spacing and height across screen sizes

---

src/components/Navbar.css
src/components/Navbar.js

added a link to the careers page and modified with css

added a link tag to the careers page and modified the css
